import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="flex space-x-3 p-6 underline text-blue-600">
          <Link href="/products">Products</Link>
          <Link href="/brands">Brands</Link>
          <Link href="/transactions">Transactions</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
